In [1]:
from utils import import_data
from prepro import data


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hamza\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:

train , val ,test, encoder_instance = import_data(encoders_data=True)
data_class = data(train ,val ,test)

Filec:\Users\Hamza\Documents\project\NLP\data\train.tsv is already download
Filec:\Users\Hamza\Documents\project\NLP\data\validation.tsv is already download
Filec:\Users\Hamza\Documents\project\NLP\data\test.tsv is already download
Filec:\Users\Hamza\Documents\project\NLP\data\text_prepare_tests.tsv is already download
Filec:\Users\Hamza\Documents\project\NLP\data\encoding.json is already download


In [3]:
data_class.clean_and_encode_data(encoder=encoder_instance)

14:55:35.47 >>> Call to data.clean_and_encode_data in File "c:\Users\Hamza\Documents\project\NLP\text_as_bagofword\prepro.py", line 137
14:55:35.47 .......... self = <prepro.data object at 0x000001E847BDFDF0>
14:55:35.47 .......... encoder = <prepro.encode_label object at 0x000001E858973A30>
14:55:35.47 .......... len(encoder) = 100
14:55:35.47  137 |     def clean_and_encode_data(self, encoder):
14:55:35.47  139 |         self.train = data.clean_datafram(self.train)
14:55:58.44  140 |         self.val = data.clean_datafram(self.val)
14:56:06.58  141 |         self.test = data.clean_datafram(self.test, test=True)
14:56:11.65  143 |         self.train = data.encode_datafram_label(encoder, self.train)
14:56:11.99  144 |         self.val = data.encode_datafram_label(encoder, self.val)
14:56:12.13  146 |         self.x_train_df , self.x_train, self.y_train = self.train.iloc[:,0],self.train.iloc[:,0].values, np.stack(self.train.iloc[:, 1].values)
14:56:12.22  147 |         self.x_val_df,sel

In [4]:
data_class.y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [6]:
from model import random_model

In [7]:
random_model = random_model()

In [8]:
random_model.fit(data_class.x_train , data_class.y_train)

In [9]:
y_pred = random_model.transform(data_class.x_val)

In [10]:
data_class.y_val

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [11]:
from model import metric

In [12]:
metric(data_class.y_val , y_pred)

{
  "precision": 0.08430465837009342,
  "recall": 0.08498695997278603,
  "f1": 0.08459023258236559
}


In [13]:
y_pred_train = random_model.transform(data_class.x_train)

In [14]:
metric(data_class.y_train , y_pred_train)

{
  "precision": 0.08533223720559531,
  "recall": 0.08580829805830234,
  "f1": 0.08556367246224784
}


In [15]:
data_class.x_train

array(['judg int number odd even binari way',
       'electron differ cordova implement wrap cordova api use nodej api electron',
       'depend insid warpackag vs share librari', ...,
       'systeminvalidoperationexcept specifi cast materi systemint32 type nullabl countri type valid',
       'python join two array key column', 'pars xml use xsd php'],
      dtype=object)

In [33]:
from model import rule_based

In [34]:
rulbased = rule_based(encoder_instance.class_to_index)

In [35]:
encoder_instance.class_to_index

{'.net': 0,
 'ajax': 1,
 'algorithm': 2,
 'android': 3,
 'angularjs': 4,
 'apache': 5,
 'arrays': 6,
 'asp.net': 7,
 'asp.net-mvc': 8,
 'c': 9,
 'c#': 10,
 'c++': 11,
 'class': 12,
 'cocoa-touch': 13,
 'codeigniter': 14,
 'css': 15,
 'csv': 16,
 'database': 17,
 'date': 18,
 'datetime': 19,
 'django': 20,
 'dom': 21,
 'eclipse': 22,
 'entity-framework': 23,
 'excel': 24,
 'facebook': 25,
 'file': 26,
 'forms': 27,
 'function': 28,
 'generics': 29,
 'google-maps': 30,
 'hibernate': 31,
 'html': 32,
 'html5': 33,
 'image': 34,
 'ios': 35,
 'iphone': 36,
 'java': 37,
 'javascript': 38,
 'jquery': 39,
 'json': 40,
 'jsp': 41,
 'laravel': 42,
 'linq': 43,
 'linux': 44,
 'list': 45,
 'loops': 46,
 'maven': 47,
 'mongodb': 48,
 'multithreading': 49,
 'mysql': 50,
 'node.js': 51,
 'numpy': 52,
 'objective-c': 53,
 'oop': 54,
 'opencv': 55,
 'osx': 56,
 'pandas': 57,
 'parsing': 58,
 'performance': 59,
 'php': 60,
 'pointers': 61,
 'python': 62,
 'python-2.7': 63,
 'python-3.x': 64,
 'qt': 65,


In [37]:
pred_r = rulbased.transform(data_class.x_train_df)

In [39]:
metric(y_pred=pred_r,y_test=data_class.y_train)


{
  "precision": 0.0007215798693783232,
  "recall": 0.022004764271392092,
  "f1": 0.0013926564160113859
}


c:\Users\Hamza\Documents\project\NLP\.venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
data_class.y_train[2]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
pred_r[2] == data_class.y_train[2]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [48]:
from model import metric1

In [52]:
metric1(data_class.y_train, pred_r)

0.0051
0.0013926564160113859
0.01948449655600501


In [53]:
metric1(data_class.y_train , y_pred_train)

0.006733333333333333
0.08556367246224784
0.019509780292469817


In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer 

In [64]:
vectorizer = TfidfVectorizer()
feature_train = vectorizer.fit_transform(data_class.x_train)
feature_val = vectorizer.transform(data_class.x_val)
feature_test = vectorizer.transform(data_class.x_test)

In [61]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression

In [65]:
clf = MultiOutputClassifier(LogisticRegression()).fit(feature_train, data_class.y_train)

In [68]:
pred_for_train = clf.predict(feature_train)
pred_for_val = clf.predict(feature_val)

In [78]:
encoder_instance.decode(pred_for_train[99])

['javascript', 'jquery']

In [79]:
metric1(data_class.y_train, pred_for_train)

0.2785
0.555870929577654
0.2717931744269514


In [80]:
metric(y_pred=pred_for_train,y_test=data_class.y_train)


{
  "precision": 0.8872251720157364,
  "recall": 0.4307209816455588,
  "f1": 0.555870929577654
}


c:\Users\Hamza\Documents\project\NLP\.venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
